<?php

namespace Shapeup\Service;

use Shapeup\Form;
use Shapeup\Hydrator;
use Shapeup\InputFilter;
use Shapeup\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-22 at 13:32:43.
 */
class AbstractServiceClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractServiceClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractServiceClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::hydrate
     * @todo   Implement testHydrate().
     */
    public function testHydrate()
    {
        $this->object
                ->setModel(new Model\Shot)
                ->setHydrator (new Hydrator\Shot);
        $data = array(
            'angle' => 45,
            'velocity' => 60,
            'initialHeight' => 100,
            'userAgentString' => 'oiajfpoaiwepo',
            'userId' => 3,
        );
        $this->getObject()->hydrate();
        $model = $this->object->getModel();
        foreach ($data as $key => $value) {
            $getMethod = 'get' . ucfirst(($key));
            $model = $this->object->getModel();
            $this->assertSame($data[$key],$model->$getMethod());
        }
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        // Remove the following lines when you implement this test.
        // MYTODO when you figure out mocking
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getDb
     * @todo   Implement testGetDb().
     */
    public function testGetDb()
    {
        // Remove the following lines when you implement this test.
        // MYTODO when you figure out mocking
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setDb
     * @todo   Implement testSetDb().
     */
    public function testSetDb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setModel
     * @todo   Implement testSetModel().
     */
    public function testSetModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getHydrator
     * @todo   Implement testGetHydrator().
     */
    public function testGetHydrator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setHydrator
     * @todo   Implement testSetHydrator().
     */
    public function testSetHydrator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getForm
     * @todo   Implement testGetForm().
     */
    public function testGetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setForm
     * @todo   Implement testSetForm().
     */
    public function testSetForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getInputFilter
     * @todo   Implement testGetInputFilter().
     */
    public function testGetInputFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setInputFilter
     * @todo   Implement testSetInputFilter().
     */
    public function testSetInputFilter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getServiceManager
     * @todo   Implement testGetServiceManager().
     */
    public function testGetServiceManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setServiceManager
     * @todo   Implement testSetServiceManager().
     */
    public function testSetServiceManager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::getIsDataValidated
     * @todo   Implement testGetIsDataValidated().
     */
    public function testGetIsDataValidated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shapeup\Service\AbstractServiceClass::setIsDataValidated
     * @todo   Implement testSetIsDataValidated().
     */
    public function testSetIsDataValidated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
